
baseUrl=https://us-cd-fnol-assignments-command-api.claims.global

authenticateEndpoint=/v1/apiclient/authenticate

saveCMSNoteEndpoint=/v1/apiclient/savecmsnote

clientId=1394

clientSecret=TUdfQVBJVGVzdGluZ0FQSVByb3BlcnR5VmVoaWNsZTIwMjYwODExMTA0MjQ5NjUz